import type { EquipmentItem } from "@/types/content";

export const equipment: EquipmentItem[] = [
  "Electric Smart Torque Tool 30Nm-2700Nm",
  "Hydraulic Smart Torque Tool",
  "Multipurpose Wellhead Cleaner",
  "VX/AX Gasket Tool",
  "Flying Lead Orientation Tool (FLOT)",
  "Linear Valve Override Tool",
  "Dirty Work Pack",
  "18\" Super Grinder",
  "Super ZipJet",
  "50L Spring Compensator",
  "Linear Actuator Override Tool (LAOT)",
  "Lock Out Tool (LOT)",
  "5.5\" Hub Cleaning Tool",
  "Wellhead Acid Plug",
  "10k Intensifier",
  "ROV Valve Handle Assembly",
  "Electric Cl 1-4 Torque Tool",
  "Torque Tool Adapter 17D to 17H",
  "Jupiter 2 TTCS",
  "Schilling T4",
  "Schilling Atlas",
  "Function Manifold",
  "Back Seal Test Panel",
  "IHPU 10KPSI",
  "Dirty Work Pump",
  "Tooling Skid",
  "ROV Super Grinder",
  "Stanley GR29",
  "Softline Cutter",
  "Stanley IW12",
  "ROV Knife",
  "ICS Chain Saw",
  "Diamond Wire Saw",
  "Subsea Shear Cutter",
  "Dynaset HPW 520",
  "Dynaset HPW 420",
  "Flexiclean Tool",
  "Multipurpose Cleaning Tool",
  "Wire Brush Cleaning Tool",
  "4\" Dredger",
  "6\" Dredger",
  "8\" Dredger",
  "10\" Dredger",
];

export const equipmentStackPhotos = [
  {
    src: "/images/equipment/stack-1.png",
    alt: "Subsea tooling photograph 1",
    objectPosition: "center 46%",
  },
  {
    src: "/images/equipment/stack-2.png",
    alt: "Subsea tooling photograph 2",
    objectPosition: "center 42%",
  },
  {
    src: "/images/equipment/stack-3.png",
    alt: "Subsea tooling photograph 3",
    objectPosition: "center 38%",
  },
  {
    src: "/images/equipment/stack-4.jpg",
    alt: "Subsea tooling photograph 4",
    objectPosition: "center 58%",
  },
  {
    src: "/images/equipment/stack-5.jpg",
    alt: "Subsea tooling photograph 5",
    objectPosition: "center 52%",
  },
] as const;
